### PR TITLE
Show all IP address families (un-shun IPv6)

### PR DESCRIPTION
**Pull request by snobu**
Why you no add IPv6 to everything, Microsoft?
Before/After commit: http://i.imgur.com/VNdjdGB.png

Please consider doing this in the final shipping product too.

### CODE REVIEW

**Comment by bfjelds** [comment]
We were aiming for simplicity in our initial sample, but this is a great idea.  For clarity sake, can you separate the v6 and v4 (create an "IPv4 address" label and an "IPv6 address" label).  Thanks for helping improve this sample!!

**Comment by ooeygui** [comment]
There was a collision on this change and can no longer be merged. Would you mind merging upstream changes?

**Comment by snobu** [comment]
I've tried doing v4/v6 in separate boxes but at low resolution that space gets really cramped really fast. https://ms-iot.github.io/content/images/DefaultAppRpi2.png I'll see what i can do.

**Comment by snobu** [comment]
Nevermind me, i just saw you guys re-did the whole UI. I think it looks great! With v6! Congrats!

**Comment by bfjelds** [comment]
Thanks for pointing out the v6 omission ... we really appreciate the feedback!

**Pull request closed without merging**
