### PR TITLE
Fix null result and clear result list.

### PR DESCRIPTION
**Pull request by phenixita**
When result from API is null avoid crash.

Clear result list every click because it was Always adding at the bottom.

### CODE REVIEW

**Review by IoTGirl — COMMENTED** [review]
Looks good to me but should something happen if emotionResult is NULL?
Does emotionResult need to be thread safe? Critical section?

**Comment by phenixita** [comment]
It doesn't seem a critical section to me.
If emotionResult is null the GUI could state "Detection Failed" or something like that.

**Comment by dcrck** [comment]
Looks good to me.

Would you mind adding the "Detection failed" statement to the ResultBox when emotionResult is null just for completeness?

Thanks!

**Review by IoTGirl — APPROVED** [review]
Approved by Derek

**Pull request merged**
