### PR TITLE
Update layout so it better adapts to small screens like a typical 800x480 IoT LCD

### PR DESCRIPTION
**Pull request by dotMorten**
This issue addresses #70

### CODE REVIEW

**Comment by bfjelds** [comment]
Thanks!  This is an awesome update ... we are going to run through some testing before merging.

**Comment by dotMorten** [comment]
Thanks. Let me know if you need me to make any adjustments. Layout should stay more or less the same on higher resolution screens, but had to move some scrollable areas around (or add scrollable areas)

**Comment by dotMorten** [comment]
...to work with even smaller screens some more serious changes are needed (ie reduce font sizes and margins). Would be good to use some adaptive triggers to do that so really small screens work too, but I didn't want to go ahead and make so serious changes to your app just yet (and the above changes would still be needed and a step in the right direction)

**Comment by bfjelds** [comment]
Agreed.  We use this code as the actual default app on our device, so we need to rope in a couple people (designers, etc) before merging this.  The only issues I've seen with the changes are on the OOBEWelcome screen (where the Cancel and Next buttons show up on top of eachother).  Otherwise, your changes really highlight what your second comment.  We should be able to move forward with this on Monday ... thanks again for helping improve this sample!!

**Comment by dotMorten** [comment]
I'll fix the cancel/next issue before Monday. Good catch!

**Comment by bfjelds** [comment]
Thanks for fixing up the cancel/next button.  I have our designer folks taking a look today.

**Pull request merged**
